### PR TITLE
Added @RequiresApi(Build.VERSION_CODES.N) for NotificationChannel related code

### LINKED ISSUE #8: Field requires API level 24, but the min SDK level is 23
https://github.com/ailabstw/social-distancing-android/blob/8e4e761dc681a0a71a48c609f58c8b199c41c84f/SocialDistance/src/main/java/tw/gov/cdc/exposurenotifications/nearby/NotificationHelper.kt#L181

https://github.com/ailabstw/social-distancing-android/blob/8e4e761dc681a0a71a48c609f58c8b199c41c84f/SocialDistance/src/main/java/tw/gov/cdc/exposurenotifications/nearby/NotificationHelper.kt#L185

`NotificationManager.IMPORTANCE_NONE` and `NotificationManager.IMPORTANCE_DEFAULT` are added in [API level 24](https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_DEFAULT).

### PR DESCRIPTION
**Pull request by seventhmoon**
Added ```@RequiresApi(Build.VERSION_CODES.N)``` for NotificationChannel related code for fixing #8

### CODE REVIEW

**Comment by catcutecat** [comment]
It seems that adding ```@RequiresApi(Build.VERSION_CODES.N)``` is only to suppress the warnings but prevent calling on Android M or below. I'd prefer to leave the warnings alone instead of just suppressing them.

**Comment by seventhmoon** [comment]
The variable `channelInfo` is inside `generateNotification()` / `createNotificationChannelIfNeeded()`

`generateNotification()` will call [`NotificationCompat.Builder`](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#Builder(android.content.Context,%20java.lang.String))

`createNotificationChannelIfNeeded()` has the following condition check
``` if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) ```

So it is checked in upper levels. 

The annotation is not to suppress the warnings (i.e. not ``` @SuppressLint("InlinedApi")```)
, it is to tell the compiler that this method requires SDK 24. All upper levels method calling this method should also be either bounded by condition check or also requires SDK 24.

**Comment by catcutecat** [comment]
I don't have Android M or N at hand so I tried ```@RequiresApi(Build.VERSION_CODES.R)``` and use Android O and Q phones to get the channel info. I also tried calling a test function marked with ```@RequiresApi(Build.VERSION_CODES.R)```. Nothing happened, no blocking to access the channel info or calling the test function.

**Comment by seventhmoon** [comment]
Yes. This PR is not fixing any crash / incompatibility.
It is to make the code more readable, and compiler friendly.

**Comment by catcutecat** [comment]
We need someone's help testing on Android M devices.

In my memory, ```@RequiresApi``` makes apps crash when calling from lower Android versions. However, I tried ```@RequiresApi(Build.VERSION_CODES.R)``` testing on Android O and Q, just nothing happened.

I agree that adding ```@RequiresApi(Build.VERSION_CODES.N)``` makes the code more readable. But I want to make sure it won't introduce new crashes on Android M devices mostly hold by senior citizens.

**Comment by catcutecat** [comment]
We need someone's help checking on Android M devices. I agree that this will make the code more readable and compiler-friendly. But we want to make sure adding this annotation won't introduce new crashes on Android M devices mostly hold by senior citizens. Currently, there's no related crash report on Play Console.

**Pull request merged**
